###
POST http://localhost:8080/signup
Authorization: Basic super_secret_admin nospaces
Content-Type: application/json

{
  "username": "SmithJ",
  "password": "password123",
  "fullName": "Joe Smith"
}

###

POST http://localhost:8080/signup
Authorization: Basic super_secret_admin nospaces
Content-Type: application/json

{
  "username": "Jenkinsc",
  "password": "pa$$word",
  "fullName": "Carol Jenkins"
}

###

POST http://localhost:8080/signup
Authorization: Basic super_secret_admin nospaces
Content-Type: application/json

{
  "username": "Michaelsd",
  "password": "PaSsWord!",
  "fullName": "Dan Michaels"
}

###

POST http://localhost:8080/signup
Authorization: Basic super_secret_admin nospaces
Content-Type: application/json

{
  "username": "Taylorj",
  "password": "qwerty123",
  "fullName": "Jason Taylor"
}


###

POST http://localhost:8080/signup
Authorization: Basic super_secret_admin nospaces
Content-Type: application/json

{
  "username": "Guyb",
  "password": "pass",
  "fullName": "Buddy Guy"
}




###
POST http://localhost:8080/signup
Authorization: Basic Guyb pass
Content-Type: application/json

{
  "username": "dude2",
  "password": "pass",
  "fullName": "Another Dude"
}

###
POST http://localhost:8080/signup
Authorization: Basic super_secret_admin nospaces
Content-Type: application/json

{
  "username": "dude2",
  "password": "pass"
}

###
GET http://localhost:8080/order-details/1
Authorization: Basic Guyb pass
