spring:
  datasource:
#    url: pass on commandline with -Dspring.datasource.url=jdbc:xyz
#    username: pass on commandline with -Dspring.datasource.username=xyz
#    password: pass on commandline with -Dspring.datasource.password=xyz
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    log-request-details: true
  sql:
    init:
      mode: never
logging:
  level:
    org.springframework.web: DEBUG